# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x05\x61i.v1\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"s\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\x1f\n\x07history\x18\x04 \x03(\x0b\x32\x0e.ai.v1.Message\x12\x0f\n\x07use_rag\x18\x05 \x01(\x08\"X\n\tReference\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07snippet\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x02\"D\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12$\n\nreferences\x18\x02 \x03(\x0b\x32\x10.ai.v1.Reference\"1\n\x12StreamChatResponse\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32{\n\tAIService\x12/\n\x04\x43hat\x12\x12.ai.v1.ChatRequest\x1a\x13.ai.v1.ChatResponse\x12=\n\nStreamChat\x12\x12.ai.v1.ChatRequest\x1a\x19.ai.v1.StreamChatResponse0\x01\x42 Z\x1ekeep-api/internal/grpc/pb;aipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036keep-api/internal/grpc/pb;aipb'
  _globals['_MESSAGE']._serialized_start=27
  _globals['_MESSAGE']._serialized_end=67
  _globals['_CHATREQUEST']._serialized_start=69
  _globals['_CHATREQUEST']._serialized_end=184
  _globals['_REFERENCE']._serialized_start=186
  _globals['_REFERENCE']._serialized_end=274
  _globals['_CHATRESPONSE']._serialized_start=276
  _globals['_CHATRESPONSE']._serialized_end=344
  _globals['_STREAMCHATRESPONSE']._serialized_start=346
  _globals['_STREAMCHATRESPONSE']._serialized_end=395
  _globals['_AISERVICE']._serialized_start=397
  _globals['_AISERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
